version: "3.7"
services:
  api:
    volumes:
      - .:/app
    links:
      - redis
      - db
    environment:
      - SQLALCHEMY_DATABASE_URI=postgres://postgres:pg_pass@db:5432/main
    # command: sh -c 'wait-for db:5432 -- python /app/main.py'
    depends_on:
      - redis
      - db

  worker:
    volumes:
      - ./:/app
    command: sh -c 'wait-for redis:6379 -- celery -A app.celery worker --loglevel=info'
