version: "3.7"
services:

  api:
    build: "./"
    image: "api"
    ports:
      - "8080:80"
    links:
      - redis
      - db
    environment:
      - SQLALCHEMY_DATABASE_URI=postgres://postgres:pg_pass@db:5432/main
    depends_on:
      - redis
      - db

  redis:
    hostname: "redis"
    image: "redis:latest"
    ports:
      - "6379:6379"

  worker:
    image: "api"
    links:
      - redis
    command: sh -c 'wait-for redis:6379 -- celery -A app.celery worker --loglevel=info'
    depends_on:
      - redis
      - api
      - db

  db:
    image: postgres:11.1
    environment:
      POSTGRES_DB: main
      POSTGRES_PASSWORD: pg_pass
