on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, closed]

jobs:
  hello:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout pr
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: ./

      - name: Hello world action step
        id: hello
        uses: jafow/action-python-format-pr@v1
        with:
          target-file-path: ${{ github.workspace }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.fileslist }}"
